### ISSUE TITLE
finetuning.ipynb typo

### ISSUE THREAD

**Issue by alecchristie888** [acceleratescience/large-language-models#6]
In finetuning.ipynb I think Agent in the code below should be 'RAGAgent'. I'm relatively inexperienced with github so hope this is the 'right' way to raise an issue/suggest edits.

`clinton = Agent(model_config, database_config=database_config, local=True)`

`clinton = RAGAgent(model_config, database_config=database_config, local=True)`

**Comment by rkdan** [comment]
Hi @alecchristie888, thanks for catching that. Change has been made.
